config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords:     'customers/passwords',
    registrations: 'customers/registrations'
  }
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htm

  scope module: :public do
    root :to => "homes#top"
    resources :items, only: [:index, :show] do
     resource :bookmarks, only: [:create, :destroy]
    end
    get 'bookmarks' => 'bookmarks#index'
    resources :customers,only: [:edit,:update]
    get 'customers/:id/my_page' => 'customers#show', as: 'my_page'
    get 'customers/:id' => 'customers#show'
    put 'customers/:id/withdrawal' =>  'customers#withdrawal', as: 'customers_withdrawal'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]
     resources :requests, only: [:create]
    post 'order/comfirm' => 'orders#comfirm'
    get 'order/thanks' => 'orders#thanks'
    put 'order/:id/item_return' => 'orders#item_return', as: 'item_return'
    resources :orders, only: [:new, :create, :index, :show ]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KATAKASU</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body>
        <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-info">
          <a class="navbar-brand" href="/">KATAKASU</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <!-- カスタマー側がログインしたら -->
              <% if customer_signed_in? %>
                <li class='welcome'>ようこそ、<%= current_customer.name %>さん！</li>
                <li><%=link_to'商品一覧',items_path,class: 'nav-link' %></li>
                <li><%=link_to'マイページ', my_page_path(current_customer),class: 'nav-link' %></li>
                <li><%=link_to'ログアウト', destroy_customer_session_path, method: :delete, class: 'nav-link' %></li>
                <li><%=link_to'カート',  cart_items_path,class: 'nav-link' %></li>
              <% else %>
                <li><%=link_to'商品一覧', items_path, class: 'nav-link' %></li>
                <li><%=link_to'ログイン', new_customer_session_path,class: 'nav-link' %></li>
                <li><%=link_to'新規登録', new_customer_registration_path, class: 'nav-link' %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
<!-- flashにメッセージがある時 -->
    <% if flash.any? %>
          <script type="text/javascript">
            <% flash.each do |key, value| %>
              <% key = "success" if key == "notice" %>
              <% key = "error" if key == "alert" %>
              toastr['<%= key %>']('<%= value %>');
            <% end %>
          </script>
    <% end %>

    <%= yield %>
    <footer class="mt-5 d-flex justify-content-center">
      <p>&copy; KATAKASU</p>
    </footer>
  </body>
</html>